### ISSUE TITLE
README info for non-seasoned C++ users

### ISSUE THREAD

**Issue by JohnMoutafis** [AtheS21/SymspellCPP#6]
Can you please update the README (or this issue if an update is not convenient) with instructions for compilation and linking/usage as a third-party library on projects?

Also although `SymSpellTest.cpp` provides a usage example, a small usage/guideline example will be extremely helpful on the README.

**Comment by AtheS21** [comment]
Sorry for the late response. Unfortunately I didn't intend to create a library out of this at first, as you can see, half of the code is in the header file (helpers.h) so making a library out of the current state of the project is really not worth the trouble. I need to clean up the header files and then add build instructions later when I have some free time. For now, I recommend including the source file into your project if you need to.

**Comment by JohnMoutafis** [comment]
Good to know @AtheS21.
Thank you
