### ISSUE TITLE
Issues using SymspellCPP in a project with boost

### ISSUE THREAD

**Issue by JohnMoutafis** [AtheS21/SymspellCPP#7]
I am having compilation errors when trying to use symspell in a project based on boost. 

Example:

``` /usr/local/include/boost/algorithm/string/detail/finder.hpp: In member function ‘boost::iterator_range<Iterator> boost::algorithm::detail::last_finderF<SearchIteratorT, PredicateT>::findit(ForwardIteratorT, ForwardIteratorT, std::forward_iterator_tag) const’:
/usr/local/include/boost/algorithm/string/detail/finder.hpp:150:34: error: expected unqualified-id before ‘=’ token
  150 |                     result_type M=first_finder( Begin, End );
      |                                  ^
/usr/local/include/boost/algorithm/string/detail/finder.hpp:151:39: error: expected primary-expression before ‘;’ token
  151 |                     result_type Last=M;
      |                                       ^
/usr/local/include/boost/algorithm/string/detail/finder.hpp:153:30: error: expected primary-expression before ‘)’ token
  153 |                     while( M )
      |                              ^
/usr/local/include/boost/algorithm/string/detail/finder.hpp:155:31: error: expected primary-expression before ‘;’ token
  155 |                         Last=M;
      |                               ^
/usr/local/include/boost/algorithm/string/detail/finder.hpp:156:26: error: expected primary-expression before ‘=’ token
  156 |                         M=first_finder( ::boost::end(M), End );
      |                          ^
/usr/local/include/boost/algorithm/string/detail/finder.hpp:156:55: error: no matching function for call to ‘end()’
  156 |                         M=first_finder( ::boost::end(M), End );
      |                                                       ^
```

So far I tried including your code to the project as a third party and importing the SymSpell.h once into a guarded header.
When that produced the errors above, I tried including your code into a namespace to no avail.

Any idea on how to overcome those issues?
What modifications need to be applied to the code?

**Comment by AtheS21** [comment]
It looks as though you are using some boost functions on the output of symspell?

From that stack trace alone I cannot determine which function you are using but maybe that the boost function expects a different parameter (type) than the one you are passing to it? It would be helpful if you can show the code snippet of how you are using boost and symspell together

**Comment by JohnMoutafis** [comment]
I am not using the output of symspell in a boost function, they just coexist in the project... 

I believe that the errors are related to what is described in this issue: [https://stackoverflow.com/questions/7641167/g-expected-unqualified-id-before-token/7654457#7654457](https://stackoverflow.com/questions/7641167/g-expected-unqualified-id-before-token/7654457#7654457) (preprocessor damaging the code somehow)

**Comment by AtheS21** [comment]
If that's the case, you can try changing the name of the macro in helpers.h and see if it fixed the problem

`#define Dictionary unordered_map
#define HashSet unordered_set
#ifdef UNICODE_SUPPORT
#	define xstring wstring
#	define xchar wchar_t
#	define xifstream wifstream
#	define xstringstream wstringstream
#	define isxspace iswspace
#	define xregex wregex
#	define xsmatch wsmatch
#	define to_xstring to_wstring
#	define XL(x) L##x
#	define xcout wcout
#else
#	define xstring string
#	define xchar char
#	define xifstream ifstream
#	define xstringstream stringstream
#	define isxspace isspace
#	define xregex regex
#	define xsmatch smatch
#	define to_xstring to_string
#	define XL(x) x
#	define xcout cout
#endif`

just add a prefix to the names just in case, maybe the macros here conflict with some function in boost. For example:
`#define SS_Dictionary unordered_map`

**Comment by JohnMoutafis** [comment]
I tried what you suggested and some of the compilation errors were resolved.

Another change that is needed to compile side by side with boost is in the SymSpell.h: `#define M` to `#define SS_M` because that M is used in a lot of places in boost.

Thank you for your input, it was very helpful!
